In [75]:
print('Hello World!')

Hello World!

PACKAGE IMPORTS

In [76]:
import pandas as pd

DATA IMPORTS

In [77]:
url = 'https://raw.githubusercontent.com/mnorton365/Python/refs/heads/main/healthcare-dataset-stroke-data.csv'
df = pd.read_csv(url)
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,.,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24,never smoked,1

In [162]:
def better_df_info(df):
    print(100*'-')
    print('UDF - Better DataFrame Info:'.center(100))

    # SHAPE
    print('\033[4m'+'Shape:'+'\033[0m')
    print(f'Row Count:      {df.shape[0]:,}')
    print(f'Columnn Count:  {df.shape[1]:,}','\n')

    # DATA TYPES
    df_dt = df.dtypes.to_frame().rename(columns={'0':'Data Type'})
    display(df_dt)

    # MISSING VALUES
    print('\033[4m'+'Missing Values:'+'\033[0m')
    df_mv = pd.DataFrame({
        'Null Values (#)': df.isna().sum(),
        'Null Values (%)': df.isna().sum() / len(df) * 100,
        'Non-Null Values (#)': df.count(),
        'Non-Null Values (%)': df.count() / len(df) * 100})
    df_mv['Null Values (#)'] = df_mv['Null Values (#)'].map('{:,}'.format)
    df_mv['Null Values (%)'] = df_mv['Null Values (%)'].map('{:.2f}%'.format)
    df_mv['Non-Null Values (#)'] = df_mv['Non-Null Values (#)'].map('{:,}'.format)
    df_mv['Non-Null Values (%)'] = df_mv['Non-Null Values (%)'].map('{:.2f}%'.format)
    display(df_mv)

    # WORKSPACE
    df2 = pd.DataFrame({
        'Distinct (#)': [(f'{x:,}') for x in df.nunique()],
        'Data Type': df.dtypes})
    display(df2)

    df3 = pd.DataFrame(df2['Data Type'].value_counts().rename_axis(None))
    display(df3)
    print(100*'-')

better_df_info(df)

----------------------------------------------------------------------------------------------------
                                    UDF - Better DataFrame Info:
Shape:
Row Count:      5,110
Columnn Count:  12

                         0
id                   int64
gender              object
age                float64
hypertension         int64
heart_disease        int64
ever_married        object
work_type           object
Residence_type      object
avg_glucose_level  float64
bmi                float64
smoking_status      object
stroke               int64

Missing Values:

,Null Values (#),Null Values (%),Non-Null Values (#),Non-Null Values (%)
id,0,0.00%,"5,110",100.00%
gender,0,0.00%,"5,110",100.00%
age,0,0.00%,"5,110",100.00%
hypertension,0,0.00%,"5,110",100.00%
heart_disease,0,0.00%,"5,110",100.00%
ever_married,0,0.00%,"5,110",100.00%
work_type,0,0.00%,"5,110",100.00%
Residence_type,0,0.00%,"5,110",100.00%
avg_glucose_level,0,0.00%,"5,110",100.00%
bmi,201,3.93%,"4,909",96.07%
smoking_status,0,0.00%,"5,110",100.00%
stroke,0,0.00%,"5,110",100.00%

                  Distinct (#) Data Type
id                       5,110     int64
gender                       3    object
age                        104   float64
hypertension                 2     int64
heart_disease                2     int64
ever_married                 2    object
work_type                    5    object
Residence_type               2    object
avg_glucose_level        3,979   float64
bmi                        418   float64
smoking_status               4    object
stroke                       2     int64

         count
object       5
int64        4
float64      3

----------------------------------------------------------------------------------------------------

In [79]:
# KEEP - EXAMPLE FOR COERCING DATA TYPE

df.info()

df['bmi'] = pd.to_numeric(df['bmi'],errors='coerce')

print(3*'\n')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                5110 non-null   object
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(2), int64(4), object(6)
memory usage: 479.2+ KB




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB
None